---
swagger: '2.0'
info:
  title: networks
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.0/networks":
    post:
      operationId: bulkCreateNetwork
      summary: Bulk create networks
      description: |
        Creates multiple networks in a single request.
      produces:
      - application/json
      responses:
        '201':
          description: 201 response
          examples:
            application/json: |-
              {
                  "networks": [
                      {
                          "status": "ACTIVE",
                          "subnets": [],
                          "name": "sample_network3",
                          "provider:physical_network": null,
                          "admin_state_up": true,
                          "tenant_id": "4fd44f30292945e481c7b8a0c8908869",
                          "provider:network_type": "local",
                          "shared": false,
                          "id": "bc1a76cb-8767-4c3a-bb95-018b822f2130",
                          "provider:segmentation_id": null
                      },
                      {
                          "status": "ACTIVE",
                          "subnets": [],
                          "name": "sample_network4",
                          "provider:physical_network": null,
                          "admin_state_up": true,
                          "tenant_id": "4fd44f30292945e481c7b8a0c8908869",
                          "provider:network_type": "local",
                          "shared": false,
                          "id": "af374017-c9ae-4a1d-b799-ab73111476e2",
                          "provider:segmentation_id": null
                      }
                  ]
              }
    get:
      operationId: listNetworks
      summary: Retrieve list of networks
      description: |
        Retrieves list of networks to which the specified tenant has access.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "networks": [
                      {
                          "status": "ACTIVE",
                          "subnets": [],
                          "name": "public",
                          "admin_state_up": true,
                          "tenant_id": "rackspace",
                          "shared": true,
                          "id": "00000000-0000-0000-0000-000000000000"
                      },
                      {
                          "status": "ACTIVE",
                          "subnets": [],
                          "name": "private",
                          "admin_state_up": true,
                          "tenant_id": "rackspace",
                          "shared": true,
                          "id": "11111111-1111-1111-1111-111111111111"
                      },
                      {
                          "status": "ACTIVE",
                          "subnets": [
                              "017d8997-70ec-4448-91d9-a8097d6d60f3"
                          ],
                          "name": "RackNet",
                          "admin_state_up": true,
                          "tenant_id": "123456",
                          "shared": false,
                          "id": "2993e407-5531-4ca8-9d2a-0d13b5cac904"
                      }
                  ]
              }
  "/v2.0/networks/{network_id}":
    parameters:
    - name: network_id
      required: true
      in: path
      type: string
      description: |
        The UUID for the network.
    get:
      operationId: showNetwork
      summary: Show network
      description: |
        Retrieves information for a specified network.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "network": {
                      "status": "ACTIVE",
                      "subnets": [],
                      "name": "sameer-3",
                      "admin_state_up": true,
                      "tenant_id": "546428",
                      "shared": false,
                      "id": "4d4e772a-98e7-4409-8a3c-4fed4324da26"
                  }
              }
    put:
      operationId: updateNetwork
      summary: Update network
      description: |
        Updates a specified network.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples: {}
    delete:
      operationId: deleteNetwork
      summary: Delete network
      description: |
        Deletes a specified network and its associated resources.
      produces:
      - application/json
      responses:
        '204':
          description: 204 response
