---
swagger: '2.0'
info:
  title: security-groups
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.0/security-groups":
    get:
      operationId: listSecGroups
      summary: List Security Groups
      description: |
        Lists all Cloud Networks security groups to which the specified tenant has access.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "security_groups": [
                      {
                          "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                          "security_group_rules": [
                              {
                                  "remote_group_id": null,
                                  "direction": "egress",
                                  "protocol": null,
                                  "ethertype": "IPv6",
                                  "port_range_max": null,
                                  "security_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                                  "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                                  "port_range_min": null,
                                  "remote_ip_prefix": null,
                                  "id": "3c0e45ff-adaf-4124-b083-bf390e5482ff"
                              },
                              {
                                  "remote_group_id": null,
                                  "direction": "egress",
                                  "protocol": null,
                                  "ethertype": "IPv4",
                                  "port_range_max": null,
                                  "security_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                                  "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                                  "port_range_min": null,
                                  "remote_ip_prefix": null,
                                  "id": "93aa42e5-80db-4581-9391-3a608bd0e448"
                              },
                              {
                                  "remote_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                                  "direction": "ingress",
                                  "protocol": null,
                                  "ethertype": "IPv6",
                                  "port_range_max": null,
                                  "security_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                                  "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                                  "port_range_min": null,
                                  "remote_ip_prefix": null,
                                  "id": "c0b09f00-1d49-4e64-a0a7-8a186d928138"
                              },
                              {
                                  "remote_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                                  "direction": "ingress",
                                  "protocol": null,
                                  "ethertype": "IPv4",
                                  "port_range_max": null,
                                  "security_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                                  "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                                  "port_range_min": null,
                                  "remote_ip_prefix": null,
                                  "id": "f7d45c89-008e-4bab-88ad-d6811724c51c"
                              }
                          ],
                          "description": "default",
                          "name": "default",
                          "id": "85cc3048-abc3-43cc-89b3-377341426ac5"
                      }
                  ]
              }
    post:
      operationId: createSecGroup
      summary: Create Security Group
      description: |
        Creates a Cloud Networks security group.
      produces:
      - application/json
      responses:
        '201':
          description: 201 response
          examples:
            application/json: |-
              {
                  "security_group": {
                      "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                      "security_group_rules": [
                          {
                              "remote_group_id": null,
                              "direction": "egress",
                              "protocol": null,
                              "ethertype": "IPv4",
                              "port_range_max": null,
                              "security_group_id": "2076db17-a522-4506-91de-c6dd8e837028",
                              "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                              "port_range_min": null,
                              "remote_ip_prefix": null,
                              "id": "38ce2d8e-e8f1-48bd-83c2-d33cb9f50c3d"
                          },
                          {
                              "remote_group_id": null,
                              "direction": "egress",
                              "protocol": null,
                              "ethertype": "IPv6",
                              "port_range_max": null,
                              "security_group_id": "2076db17-a522-4506-91de-c6dd8e837028",
                              "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                              "port_range_min": null,
                              "remote_ip_prefix": null,
                              "id": "565b9502-12de-4ffd-91e9-68885cff6ae1"
                          }
                      ],
                      "description": "security group for webservers",
                      "name": "new-webservers",
                      "id": "2076db17-a522-4506-91de-c6dd8e837028"
                  }
              }
  "/v2.0/security-groups/{security_group_id}":
    parameters:
    - name: security_group_id
      required: true
      in: path
      type: string
      description: |
        The unique identifier of the security group.
    get:
      operationId: showSecGroup
      summary: Show Security Group
      description: |
        Shows information for a specified security group.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "security_group": {
                      "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                      "security_group_rules": [
                          {
                              "remote_group_id": null,
                              "direction": "egress",
                              "protocol": null,
                              "ethertype": "IPv6",
                              "port_range_max": null,
                              "security_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                              "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                              "port_range_min": null,
                              "remote_ip_prefix": null,
                              "id": "3c0e45ff-adaf-4124-b083-bf390e5482ff"
                          },
                          {
                              "remote_group_id": null,
                              "direction": "egress",
                              "protocol": null,
                              "ethertype": "IPv4",
                              "port_range_max": null,
                              "security_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                              "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                              "port_range_min": null,
                              "remote_ip_prefix": null,
                              "id": "93aa42e5-80db-4581-9391-3a608bd0e448"
                          },
                          {
                              "remote_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                              "direction": "ingress",
                              "protocol": null,
                              "ethertype": "IPv6",
                              "port_range_max": null,
                              "security_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                              "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                              "port_range_min": null,
                              "remote_ip_prefix": null,
                              "id": "c0b09f00-1d49-4e64-a0a7-8a186d928138"
                          },
                          {
                              "remote_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                              "direction": "ingress",
                              "protocol": null,
                              "ethertype": "IPv4",
                              "port_range_max": null,
                              "security_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                              "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                              "port_range_min": null,
                              "remote_ip_prefix": null,
                              "id": "f7d45c89-008e-4bab-88ad-d6811724c51c"
                          }
                      ],
                      "description": "default",
                      "name": "default",
                      "id": "85cc3048-abc3-43cc-89b3-377341426ac5"
                  }
              }
    delete:
      operationId: deleteSecGroup
      summary: Delete Security Group
      description: |
        Deletes a Cloud Networks security group.
      produces: []
      responses:
        '204':
          description: 204 response
  "/v2.0/security-group-rules":
    get:
      operationId: listSecGroupRules
      summary: List Security Group Rules
      description: |
        Lists a summary of all Cloud Networks security group rules that the specified tenant can access.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "security_group_rules": [
                      {
                          "remote_group_id": null,
                          "direction": "egress",
                          "protocol": null,
                          "ethertype": "IPv6",
                          "port_range_max": null,
                          "security_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                          "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                          "port_range_min": null,
                          "remote_ip_prefix": null,
                          "id": "3c0e45ff-adaf-4124-b083-bf390e5482ff"
                      },
                      {
                          "remote_group_id": null,
                          "direction": "egress",
                          "protocol": null,
                          "ethertype": "IPv4",
                          "port_range_max": null,
                          "security_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                          "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                          "port_range_min": null,
                          "remote_ip_prefix": null,
                          "id": "93aa42e5-80db-4581-9391-3a608bd0e448"
                      },
                      {
                          "remote_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                          "direction": "ingress",
                          "protocol": null,
                          "ethertype": "IPv6",
                          "port_range_max": null,
                          "security_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                          "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                          "port_range_min": null,
                          "remote_ip_prefix": null,
                          "id": "c0b09f00-1d49-4e64-a0a7-8a186d928138"
                      },
                      {
                          "remote_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                          "direction": "ingress",
                          "protocol": null,
                          "ethertype": "IPv4",
                          "port_range_max": null,
                          "security_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                          "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                          "port_range_min": null,
                          "remote_ip_prefix": null,
                          "id": "f7d45c89-008e-4bab-88ad-d6811724c51c"
                      }
                  ]
              }
    post:
      operationId: createSecGroupRule
      summary: Create Security Group Rule
      description: |
        Creates a Cloud Networks security group rule.
      produces:
      - application/json
      responses:
        '201':
          description: 201 response
          examples:
            application/json: |-
              {
                  "security_group": {
                      "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                      "security_group_rules": [
                          {
                              "remote_group_id": null,
                              "direction": "egress",
                              "protocol": null,
                              "ethertype": "IPv4",
                              "port_range_max": null,
                              "security_group_id": "2076db17-a522-4506-91de-c6dd8e837028",
                              "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                              "port_range_min": null,
                              "remote_ip_prefix": null,
                              "id": "38ce2d8e-e8f1-48bd-83c2-d33cb9f50c3d"
                          },
                          {
                              "remote_group_id": null,
                              "direction": "egress",
                              "protocol": null,
                              "ethertype": "IPv6",
                              "port_range_max": null,
                              "security_group_id": "2076db17-a522-4506-91de-c6dd8e837028",
                              "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                              "port_range_min": null,
                              "remote_ip_prefix": null,
                              "id": "565b9502-12de-4ffd-91e9-68885cff6ae1"
                          }
                      ],
                      "description": "security group for webservers",
                      "name": "new-webservers",
                      "id": "2076db17-a522-4506-91de-c6dd8e837028"
                  }
              }
  "/v2.0/security-group-rules/{rules-security-groups-id}":
    parameters:
    - name: rules-security-groups-id
      required: true
      in: path
      type: string
      description: |
        The unique identifier of the security group rule.
    get:
      operationId: showSecGroupRule
      summary: Show Security Group Rule
      description: |
        Shows detailed information for the specified security group rule.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "security_group_rule": {
                      "remote_group_id": null,
                      "direction": "egress",
                      "protocol": null,
                      "ethertype": "IPv6",
                      "port_range_max": null,
                      "security_group_id": "85cc3048-abc3-43cc-89b3-377341426ac5",
                      "tenant_id": "e4f50856753b4dc6afee5fa6b9b6c550",
                      "port_range_min": null,
                      "remote_ip_prefix": null,
                      "id": "3c0e45ff-adaf-4124-b083-bf390e5482ff"
                  }
              }
    delete:
      operationId: deleteSecGroupRule
      summary: Delete Security Group Rule
      description: |
        Deletes the specified rule from a Cloud Networks security group.
      produces: []
      responses:
        '204':
          description: 204 response
